### ISSUE TITLE
[BUG] pillar.example is in wrong format

### ISSUE THREAD

**Issue by mrichar1** [saltstack-formulas/virtualenv-formula#4]
The example in `pillar.example` has 2 errors:

1. `projects` - the code actually iterates over `virtualenv.project.items()`
2. `path` - the code actually looks for `options.name`

**Comment by myii** [comment]
@mrichar1 Thanks for this report.  I can see the issue, where `name` doesn't appear under the `mysite1` key.  Would you be able to add this in a PR?
